### ISSUE TITLE
Pairwise - Affichage de la liste des modalités à sélectionner 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic-DSFR#142]
Toutes les options sont [Object Object], que ce soit dans le composant ou dans un json "bien formé" 
[IssueEno927.json](https://github.com/InseeFr/Lunatic-DSFR/files/14586216/IssueEno927.json)

**Comment by ddecrulle** [comment]
Il ne s'agit pas d'un bug Lunatic-dsfr mais lunatic. Le composant pairwise ne sait pas afficher les options ayant un label bien formé. Pour que l'affichage soit correcte il faut que les labels soit des string et non de type `{"value": "une value","type":"VTL|MD"}`

**Comment by AnneHuSKa** [comment]
@ddecrulle : c'est la même chose pour les Dropdown hors suggester donc  ? Ce que je constate en recette stromaeV3.dsfr par exemple

**Comment by ddecrulle** [comment]
Oui j'ai un souci avec le dropdown j'attends ça https://github.com/codegouvfr/react-dsfr/pull/246
