### ISSUE TITLE
Suggester - pas d'écho si on efface une saisie et qu'on recherche de nouveau sans sortir du champ

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic-DSFR#147]
## Description du bug

Suggester : lorsqu'on a choisi un écho, qu'on efface cet écho et qu'on recherche un nouveau (ou même) libellé sans sortir de la zone de saisie, aucun écho n'est trouvé. Si on sort de la zone de saisie, la recherche fonctionne de nouveau.

=>  I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## Pour reproduire le bug

vidéo jointe
[Suggester.zip](https://github.com/InseeFr/Lunatic-DSFR/files/15109717/Suggester.zip)

## Comportement attendu

Des échos trouvés ou une explication ?

## Version où le bug est apparu 

3.0 Lunatic mais je ne sais pas laquelle

## Navigateurs testés 

=> Firefox

**Comment by ddecrulle** [comment]
We know this but it has been fixed but I don't know on which version

**Comment by ddecrulle** [comment]
fixed by https://github.com/InseeFr/Lunatic/pull/962

**Comment by ddecrulle** [comment]
deployed in storybook and release in v2.0.0-rc.15
