### ISSUE TITLE
Effacement de données impossible ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic-DSFR#173]
Exemple dans la vidéo jointe : le champ Input Number ne peut pas être vidé (tout est ok en Lunatic, ko en DSFR)
[QNONREG - Filtre et vidages.json](https://github.com/InseeFr/Lunatic-DSFR/files/15433531/QNONREG.-.Filtre.et.vidages.json)
[vidage_filtre.zip](https://github.com/InseeFr/Lunatic-DSFR/files/15433549/vidage_filtre.zip)

**Comment by ddecrulle** [comment]
fixed by https://github.com/InseeFr/Lunatic-DSFR/commit/2e83035d7dffcc4ebeb03256f106d26bd622f5dd
