### ISSUE TITLE
[Datepicker] onChange fails if entering value that matches current value

### ISSUE THREAD

**Issue by isMattCoding** [InseeFr/Lunatic-DSFR#93]
### To reproduce: 

* Launch storybook with `yarn storybook` 
* Navigate to the [datepicker story](http://localhost:6006/?path=/story/components-datepicker--default)
* Enter - jour: 18, mois, 01, année: 1990
* Click next, and then click previous
* Clear the année field
* Enter `199` in the année field 
* Enter `0` (value must be the same as it was previously saved as)

Expected result: 
In the année field, the value is `0199` instead of `1990`. 
When consulting the console, the onChange function was called each time the value changed, except the last time. 

Initial examination: 
The function checkSubValue (DatepickerInput.tsx, line 12) is relatively difficult to understand, but it doesn't seem to be the source of the problem. 
It seems that there is a condition that prevents the onChange function from being called if the value matches that which was already defined. 
There is a function [useOnHandleChange ](https://github.com/InseeFr/Lunatic/blob/develop/src/components/commons/use-on-handle-change.ts) in Lunatic that could be the source of the problem, investigation pending.

**Comment by isMattCoding** [comment]
I think I resolved it by adding the setDay/Month/Year in the onChange callbacks in DatepickerInput: 

``` 

    const changeDay = useCallback(
        (e: React.ChangeEvent<HTMLInputElement>) => {
					setDay(checkSubValue(2, e.target.value))
            onChange(`${year}-${month}-${checkSubValue(2, e.target.value)}`);
        },
        [year, month],
    );
    const changeMonth = useCallback(
        (e: React.ChangeEvent<HTMLInputElement>) => {
					setMonth(checkSubValue(2, e.target.value))
            onChange(`${year}-${checkSubValue(2, e.target.value)}-${day}`);
        },
        [year, day],
    );
    const changeYear = useCallback(
        (e: React.ChangeEvent<HTMLInputElement>) => {
					setYear(checkSubValue(4, e.target.value))
            onChange(`${checkSubValue(4, e.target.value)}-${month}-${day}`);
        },
        [month, day],
    );
    ```

**Comment by isMattCoding** [comment]
> I think I resolved it by adding the setDay/Month/Year in the onChange callbacks in DatepickerInput:

This helped to display the changed value, but the value of the component is not updated onChange.

**Comment by Grafikart** [comment]
Attention onChange peut changer, donc il doit être en dépendance du useCallback()
Aussi, le code du `checkSubValue` est beaucoup trop complexe. Il serait intéréssant de séparer ou de commenter l'objectif de chaque ligne

**Comment by isMattCoding** [comment]
Fixed by pr https://github.com/InseeFr/Lunatic-DSFR/pull/96.  

Merci pour ton aide @Grafikart ! 🚀
